CICD doc: Feature Branch instead of GitFlow
elastic-ipfs/elastic-ipfs pull request #10
Opened 2022-08-31 18:37 UTC by francardoso93

2022-09-01 03:19 UTC, simone-sanfratello commented
I think we should cover other operations: how to deploy in dev/staging/main, required reviews, deal with hotfix, provide examples
we should also set "owners" for each repo, people that are able to deploy, and make them consistent

2022-09-01 03:23 UTC, simone-sanfratello requested changes

2022-09-01 03:23 UTC, simone-sanfratello commented on cicd-workflows.md
> +All Elastic Provider component repositories follow the [Feature Branch Workflow strategy](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow). They can have any numbe
`dev` branch should not exists at all, it's a legacy thing from git flow and does not belong to the "feature branch" flow

2022-09-01 03:23 UTC, simone-sanfratello commented on cicd-workflows.md
> +- dev: dev (Automatic)
we should not mix flows, feature branch strategy doesnt have env branches

2022-09-01 03:23 UTC, simone-sanfratello commented on cicd-workflows.md
> +## `Dev` branch
remove

2022-09-01 12:06 UTC, francardoso93 commented on cicd-workflows.md
> +All Elastic Provider component repositories follow the [Feature Branch Workflow strategy](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow). They can have any numbe
What other approach do you think it's ideal to validate/test features that will take longer to be deployed without polluting main branch?

2022-09-01 12:12 UTC, francardoso93 commented
> I think we should cover other operations: how to deploy in dev/staging/main, required reviews, deal with hotfix, provide examples we should also set "owners" for each repo, people that are able to deploy, and make them consistent

**how to deploy in dev/staging/main:** I thought I had covered that, but feel free to suggest how to improve the descriptions that currently exist about that.
**deal with hotfix**: There is no such thing in feature branch workflow
**provide examples**: Examples of.. ?
**we should also set "owners" for each repo, people that are able to deploy, and make them consistent**:  Does that affect docs? How would you put it?

2022-09-02 12:16 UTC, simone-sanfratello commented
Can we at least remove the `dev` branch?

2022-09-02 13:13 UTC, francardoso93 commented on cicd-workflows.md
> +## `Dev` branch
Done

2022-09-02 13:13 UTC, francardoso93 commented on cicd-workflows.md
> +- dev: dev (Automatic)
Let's talk more about that one later, but removed for now

2022-09-02 13:14 UTC, francardoso93 commented
> Can we at least remove the dev branch?
Done :)

2022-09-02 13:19 UTC, simone-sanfratello approved these changes

2022-09-02 17:49 UTC, merged